services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: wonder-rabbitmq-xml
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    environment:
      RMQ_USER: ${RMQ_USER}
      RMQ_PASSWORD: ${RMQ_PASSWORD}
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"

volumes:
  rabbitmq-data: